version: 2.1

executors:
  environment:
    environment:
      IMAGE_NAME: adithcraft/circleci_gin
    docker:
      - image: cimg/go:1.18
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  test:
    executor: environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Code linting
          command: >
            go get -u golang.org/x/lint/golint
            #golint ./...
      - run:
          name: Unit tests
          command: go test -v ./...

  build:
    executor: environment
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Publish Image to Docker Hub
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $IMAGE_NAME --build-arg API_VERSION=${TAG} .
            docker push $IMAGE_NAME:latest

  deploy:
    executor: environment
    steps:
      - checkout
      - run:
          name: Deploy with Docker Compose
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose pull
            docker-compose up -d

workflows:
  ci_cd:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
            - build
